spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coupang?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    session:
      host: localhost
      port: 6379
      password: 1234
    cache:
      host: localhost
      port: 6380
      password: 1234

mybatis:
  type-aliases-package: com.coupang.marketplace.*.domain
  mapper-locations: mybatis/mapper/**/*.xml